Feat/crud filament
jl-ultras-tech/joblife-ultras.com pull request #12
Opened 2024-05-30 17:25 UTC by yanislgha

Liste des changements que je trouve logique et de l'état de ce que j'ai fait
![image](https://github.com/jl-ultras-tech/joblife-ultras.com/assets/93376918/4430686c-0049-4081-96f3-f953f4d00fbf)

2024-05-30 18:10 UTC, noxyz20 requested changes
Pas mal dans l'ensemble il manque quelque truc mais c'est top ! j'espère que tu prend du plaisir avec filament. Mes dm sont ouvert bien évidement pour toute questions/aide ! Bon courage pour la suite !

2024-05-30 18:10 UTC, noxyz20 commented on app/Models/Event.php
> +    use HasFactory;
` use HasFactory, SoftDeletes` rajouter le trait  SoftDeletes ne pas oublier l'import `use Illuminate\Database\Eloquent\SoftDeletes;`

2024-05-30 18:10 UTC, noxyz20 commented on app/Models/Contact.php
> +    use HasFactory;
use HasFactory, SoftDeletes rajouter le trait SoftDeletes ne pas oublier l'import use Illuminate\Database\Eloquent\SoftDeletes;

2024-05-30 18:10 UTC, noxyz20 commented on app/Filament/Resources/EventResource.php
> +                TextColumn::make('dateEvent')->dateTime(),
Pas trop logique de parse un datetime en datetime (pour ça le timestamp dans la migration) et va falloir aussi mettre la string pour formater https://www.php.net/manual/en/datetime.format.php

2024-05-30 18:12 UTC, noxyz20 commented on database/migrations/2024_05_30_154056_create_event_table.php
> +            $table->timestamps();
peut etre aussi rename la colonne en start_at pour etre iso avec les conventions

2024-05-30 18:33 UTC, yanislgha commented on database/migrations/2024_05_26_184126_add_infos_to_users_table.php
> +            $table->text('banner_img')->nullable();
> Essaie de voir pour les ajouter avant les timestamps et soft delete

Tu parles de quoi précisément ?

2024-06-18 06:57 UTC, noxyz20 requested changes
Pas de ressource Pivot inspire toi des permission dans la ressource UserFilament il peut y avoir une Ressource User une Ressource Prediction mais pas de Ressource UserHasPrediction c'est un model de donnée qui va service a faire des liaisons uniquement

2024-06-18 06:57 UTC, noxyz20 commented on app/Models/UserHasPrediction.php
a mettre dans un dossier Pivots avec le namespace `App\Models\Pivots`

2024-06-18 06:57 UTC, noxyz20 commented on app/Models/UserHasPrediction.php
> +class UserHasPrediction extends Model
Extend de PIvot et non model

2024-06-22 21:05 UTC, noxyz20 approved these changes
@kimjonghun

2024-06-22 21:06 UTC, sakv-dev approved these changes

2024-06-22 21:06 UTC, merged