Feat/front integrate login  register from design
jl-ultras-tech/joblife-ultras.com pull request #14
Opened 2024-05-30 19:19 UTC by sakv-dev

2024-06-01 20:11 UTC, noxyz20 requested changes
Cool dans l'ensemble ! 2-3 truc sur le js a changer selon moi pour que ce sois plus lisible

2024-06-01 20:11 UTC, noxyz20 commented on public/js/form.js
> +}
pas fan du add event listener essaie plutot de faire du ES6 en exportant une const (je peux te montrer si tu veux) et pour trigger dans le html tu peux utilisé `wire:click` c'est une directive de AlpineJS

2024-06-03 21:54 UTC, noxyz20 approved these changes
Good job sermax dev ✌🏻

2024-06-03 22:08 UTC, sakv-dev commented
J'avais oublié de modif le tailwind.config.js. normalement tu peux valider la pr

2024-06-05 17:19 UTC, yanislgha commented on resources/views/dashboard.blade.php
> -                <div class="p-6 text-gray-900">
Faudrait juste changer comme on en avais déjà parlé le nom de la var quand tu auras le temps

2024-06-05 17:19 UTC, yanislgha approved these changes

2024-06-05 17:20 UTC, sakv-dev commented on resources/views/dashboard.blade.php
> -                <div class="p-6 text-gray-900">
Ah j'ai pas touché à cette branche, mais oe tkt je changerai en variable

2024-06-05 17:20 UTC, merged